-- 코드를 작성해주세요
# SELECT I.ITEM_ID, ITEM_NAME, RARITY
# FROM ITEM_INFO AS I
# JOIN ITEM_TREE AS T
# ON I.ITEM_ID = T.ITEM_ID
# WHERE I.ITEM_ID NOT IN (T.PARENT_ITEM_ID)
# ORDER BY I.ITEM_ID DESC

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID NOT IN (
    SELECT PARENT_ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NOT NULL
    GROUP BY PARENT_ITEM_ID
)
ORDER BY ITEM_ID DESC

# SELECT PARENT_ITEM_ID
# FROM ITEM_TREE
# WHERE PARENT_ITEM_ID != NULL
# GROUP BY PARENT_ITEM_ID