# -- 코드를 작성해주세요
# # SELECT ITEM_ID, ITEM_NAME, RARITY
# # FROM ITEM_INFO
# # WHERE ITEM_ID NOT IN (
# #     SELECT PARENT_ITEM_ID
# #     FROM ITEM_TREE
# #     WHERE PARENT_ITEM_ID IS NOT NULL
# #     GROUP BY PARENT_ITEM_ID
# # )
# # ORDER BY ITEM_ID DESC

# SELECT
#     A.ITEM_ID, ITEM_NAME, RARITY, PRICE, B.ITEM_ID AS TO_, PARENT_ITEM_ID AS FROM_
# FROM
#     ITEM_INFO A
#     LEFT JOIN ITEM_TREE B
#         ON A.ITEM_ID = B.PARENT_ITEM_ID




SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS I
LEFT JOIN ITEM_TREE AS T
ON I.ITEM_ID = T.PARENT_ITEM_ID
WHERE T.PARENT_ITEM_ID IS NULL
ORDER BY I.ITEM_ID DESC