-- 코드를 입력하세요
SELECT A.USER_ID, A.PRODUCT_ID FROM ONLINE_SALE A, ONLINE_SALE B
WHERE A.USER_ID = B.USER_ID
    AND A.PRODUCT_ID = B.PRODUCT_ID
    AND A.SALES_DATE != B.SALES_DATE
GROUP BY A.USER_ID, A.PRODUCT_ID
ORDER BY A.USER_ID ASC, A.PRODUCT_ID DESC